# Generated by Django 5.2 on 2025-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longurl', models.CharField(max_length=300)),
                ('shorturl', models.CharField(max_length=20)),
            ],
        ),
    ]
