# Generated by Django 5.2 on 2025-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longurl', models.CharField()),
                ('shorturl', models.CharField()),
            ],
        ),
    ]
