# Generated by Django 5.2 on 2025-04-13 09:01

import encoder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.CharField(default=encoder.models.Url.converter),
        ),
    ]
