# Generated by Django 5.2 on 2025-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0003_alter_url_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='longurl',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
